import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@components/common/Header";
import { Footer } from "@components/common/Footer";
import { ViewTransitions } from "next-view-transitions";
import { Toaster } from "sonner";

const geistSans = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],

});

const geistMono = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="es">
        <body
          className={`${geistSans} ${geistMono} antialiased min-h-screen flex flex-col `}
        >
          <Toaster position="top-right" richColors />
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  );
}
